
## load external properties
#load:
#  properties: ${user.home}/config/my-application.properties



datasource:
  db:
    username: iv
    password: ivpass
    url: jdbc:mysql://localhost:3306/ivdb
    driver: com.mysql.jdbc.Driver



#ebean:
#  docstore:
#    url: http://127.0.0.1:9200
#    active: true
#  migration:
#   run: true





